version: '3.7'

services:
  app:
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: app.settings
      PYTHONPATH: /code
    command: daphne -b 0.0.0.0 -p 8001 app.channels:application
    init: true
    stdin_open: true
    tty: true
    working_dir: /code
    volumes:
      - .:/code
    depends_on:
      - redis
    ports:
      - 8001:8001

  redis:
    image: redis:6-buster
